Config = Config or {}

Config.SkinMale = {
    model = 'mp_m_freemode_01',
    head_blend = {
        ['firstShape'] = 21,
        ['secondShape'] = 0,
        ['thirdShape'] = 0,
        ['firstSkin'] = 21,
        ['secondSkin'] = 0,
        ['thirdSkin'] = 0,
        ['shapeMix'] = 0.5,
        ['skinMix'] = 0.5,
        ['thirdMix'] = 0.5,
    },
    face_features = {
        ['eyebrow'] = { 0, 0 },
        ['eye_opening'] = 0,
        ['nose_width_peak'] = { 0, 0 },
        ['nose_length_tip'] = { 0, 0 },
        ['nose_twist_curveness'] = { 0, 0 },
        ['lip_thickness'] = 0,
        ['cheek_width_height'] = { 0, 0 },
        ['cheek_size'] = 0,
        ['jaw_width_shape'] = { 0, 0 },
        ['chin_length_height'] = { 0, 0 },
        ['chin_shape_hole'] = { 0, 0 },
        ['neck_thickness'] = 0,
    },
    eye_color = 0,
    head_overlays = {
        ['blemishes'] = { -1, 1.0 },
        ['facial_hair'] = { -1, 1.0, 0 },
        ['eyebrows'] = { 0, 1.0, 0 },
        ['ageing'] = { -1, 1.0 },
        ['makeup'] = { -1, 1.0, 0, 0 },
        ['blush'] = { -1, 1.0, 0 },
        ['complexion'] = { -1, 1.0 },
        ['sun_damage'] = { -1, 1.0 },
        ['lipstick'] = { -1, 1.0, 0 },
        ['moles_freckles'] = { -1, 1.0 },
        ['chest_hair'] = { -1, 1.0, 0 },
        ['body_blemishes'] = { -1, 1.0 },
        ['add_body_blemishes'] = { -1, 1.0 },
    },
    hair = { 0, 0, 0, 0, 1 },
    components = {
        ['mask'] = { 0, 0 },
        ['arms'] = { 0, 0 },
        ['pants'] = { 0, 0 },
        ['bag'] = { 0, 0 },
        ['shoes'] = { 0, 0 },
        ['accessory'] = { 0, 0 },
        ['t-shirt'] = { 0, 0 },
        ['vest'] = { 0, 0 },
        ['decals'] = { 0, 0 },
        ['torso2'] = { 0, 0 },
    },
    props = {
        ['hat'] = { -1, 0 },
        ['glass'] = { -1, 0 },
        ['ear'] = { -1, 0 },
        ['watch'] = { -1, 0 },
        ['bracelet'] = { -1, 0 },
    },
}

Config.SkinFemale = {
    model = 'mp_f_freemode_01',
    head_blend = {
        ['firstShape'] = 45,
        ['secondShape'] = 45,
        ['thirdShape'] = 45,
        ['firstSkin'] = 45,
        ['secondSkin'] = 45,
        ['thirdSkin'] = 45,
        ['shapeMix'] = 0.5,
        ['skinMix'] = 0.5,
        ['thirdMix'] = 0.5,
    },
    face_features = {
        ['eyebrow'] = { 0, 0 },
        ['eye_opening'] = 0,
        ['nose_width_peak'] = { 0, 0 },
        ['nose_length_tip'] = { 0, 0 },
        ['nose_twist_curveness'] = { 0, 0 },
        ['lip_thickness'] = 0,
        ['cheek_width_height'] = { 0, 0 },
        ['cheek_size'] = 0,
        ['jaw_width_shape'] = { 0, 0 },
        ['chin_length_height'] = { 0, 0 },
        ['chin_shape_hole'] = { 0, 0 },
        ['neck_thickness'] = 0,
    },
    eye_color = 0,
    head_overlays = {
        ['blemishes'] = { -1, 1.0 },
        ['facial_hair'] = { -1, 1.0, 0 },
        ['eyebrows'] = { 0, 1.0, 0 },
        ['ageing'] = { -1, 1.0 },
        ['makeup'] = { -1, 1.0, 0, 0 },
        ['blush'] = { -1, 1.0, 0 },
        ['complexion'] = { -1, 1.0 },
        ['sun_damage'] = { -1, 1.0 },
        ['lipstick'] = { -1, 1.0, 0 },
        ['moles_freckles'] = { -1, 1.0 },
        ['chest_hair'] = { -1, 1.0, 0 },
        ['body_blemishes'] = { -1, 1.0 },
        ['add_body_blemishes'] = { -1, 1.0 },
    },
    hair = { 0, 0, 0, 0, 1 },
    components = {
        ['mask'] = { 0, 0 },
        ['arms'] = { 0, 0 },
        ['pants'] = { 0, 0 },
        ['bag'] = { 0, 0 },
        ['shoes'] = { 1, 0 },
        ['accessory'] = { 0, 0 },
        ['t-shirt'] = { 0, 0 },
        ['vest'] = { 0, 0 },
        ['decals'] = { 0, 0 },
        ['torso2'] = { 0, 0 },
    },
    props = {
        ['hat'] = { -1, 0 },
        ['glass'] = { -1, 0 },
        ['ear'] = { -1, 0 },
        ['watch'] = { -1, 0 },
        ['bracelet'] = { -1, 0 },
    },
}